<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKWZTywrXeq4hFI" failures="2" tests="20" name="Test" time="35.032" errors="0" timestamp="2022-11-23T15:53:13 IST">
  <testcase classname="testing.MyFirstTestNGTest" name="createAccount" time="0.004"/>
  <testcase classname="testing.MyFirstTestNGTest" name="deleteAccount" time="0.0"/>
  <testcase classname="testing.MyFirstTestNGTest" name="logOutFromApplication" time="0.0"/>
  <testcase classname="testing.MyFirstTestNGTest" name="login" time="0.0"/>
  <testcase classname="test_reporting.MyFirstSeleniumScript2" name="ineuronLogin" time="2.012"/>
  <testcase classname="test_reporting.MyFirstSeleniumScript" name="amazonTitle" time="3.463"/>
  <testcase classname="testing.Login" name="invalidPassword" time="0.158"/>
  <testcase classname="test_reporting.Login" name="invalidPassword" time="0.127"/>
  <testcase classname="testing.Login" name="invalidUser" time="0.11"/>
  <testcase classname="test_reporting.Login" name="invalidUser" time="0.122"/>
  <testcase classname="testing.Login" name="noEntry" time="0.077"/>
  <testcase classname="test_reporting.Login" name="noEntry" time="0.067"/>
  <testcase classname="testing.Login" name="validPassword" time="4.197"/>
  <testcase classname="test_reporting.TaskDay3" name="switchTabs" time="1.394">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at test_reporting.TaskDay3.switchTabs(TaskDay3.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- switchTabs -->
  <testcase classname="test_reporting.Login" name="validPassword" time="3.823"/>
  <testcase classname="testing.SmokeTest" name="verifyForgotPasswordLink" time="0.0"/>
  <testcase classname="testing.LoginTest" name="verifyNoEntry" time="3.002"/>
  <testcase classname="testing.SmokeTest" name="verifySocialMediaCount" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at testing.SmokeTest.verifySocialMediaCount(SmokeTest.java:37)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifySocialMediaCount -->
  <testcase classname="testing.SmokeTest" name="verifyTitle" time="0.004"/>
  <testcase classname="testing.SmokeTest" name="verifyURL" time="0.003"/>
</testsuite> <!-- Test -->
